version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:prometheus

  prometheus:
    image: quay.io/prometheuscommunity/avalanche:main
    restart: unless-stopped
    command:
      - "--port=8080"
      - "--metric-count=50"
